version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./endpoints:/app/endpoints
      - ./schemas:/app/schemas
      - ./services:/app/services
    restart: unless-stopped
    env_file:
      - .env